import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

import Breadcrumb from "../../../src/components/common/Breadcrumb";

import courseStyles from "../../../styles/Course.module.css";
export default function Course() {
  const router = useRouter();
  const { id, course } = router.query;
  // console.log(id, course);
  return (
    <div className="w-full ">
      <Head>
        <title>{course} | بیمه کارآفرین نمیاندگی بابازاده</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Breadcrumb />
      <div className="container px-24 mx-auto">
        <div className="grid grid-cols-1 gap-4 md:grid-cols-3 md:gap-x-4 gap-x-0">
          <div className="col-span-2 p-4">
            <div className={courseStyles.courseSingleMain}>
              <div className={courseStyles.courseSingleContent}>
                <div
                  className={`${courseStyles.courseSingleTopPart} bg-white border border-slate-300`}
                >
                  <div className={courseStyles.courseImageWrapper}>
                    <img
                      width="1667"
                      height="954"
                      src="https://d2ffcs5wrcif.cdn.shift8web.com/wp-content/uploads/LOW-3.jpg"
                      className="attachment-full size-full wp-post-image"
                      alt=""
                    />
                    <div className={courseStyles.videoButton}>
                      <Link href="/">
                        <a>
                          <span className="mdi mdi-play-outline flex justify-center items-center ml-2" />
                        </a>
                      </Link>
                    </div>
                  </div>
                </div>
                <div className={courseStyles.courseDesciption}>
                  <p className="text-right">
                    <span style={{ color: "#000000" }}>
                      &nbsp;آموزش react native – ساخت اپلیکیشن فروشگاهی مشابه
                      دیجی کالا
                    </span>
                    &nbsp; دوره ای است که با استفاده از تکنولوژی های{" "}
                    <span style={{ color: "#000000" }}>
                      <span style={{ color: "#0000ff" }}>
                        <a
                          style={{ color: "#0000ff" }}
                          href="https://reactapp.ir/courses/%d8%af%d9%88%d8%b1%d9%87-%d9%87%d8%a7%db%8c-%d8%a2%d9%85%d9%88%d8%b2%d8%b4%db%8c/%d8%af%d9%88%d8%b1%d9%87-%d8%ac%d8%a7%d9%85%d8%b9-react-native/"
                        >
                          react native
                        </a>
                      </span>
                      ،{" "}
                      <span style={{ color: "#0000ff" }}>
                        <a
                          style={{ color: "#0000ff" }}
                          href="https://reactapp.ir/courses/%d8%af%d9%88%d8%b1%d9%87-%d9%87%d8%a7%db%8c-%d8%a2%d9%85%d9%88%d8%b2%d8%b4%db%8c/%d8%af%d9%88%d8%b1%d9%87-%d8%ac%d8%a7%d9%85%d8%b9-react-js/"
                        >
                          react
                        </a>
                      </span>
                      ،{" "}
                      <span style={{ color: "#0000ff" }}>
                        <a
                          style={{ color: "#0000ff" }}
                          href="https://reactapp.ir/courses/%d8%af%d9%88%d8%b1%d9%87-%d9%87%d8%a7%db%8c-%d8%a2%d9%85%d9%88%d8%b2%d8%b4%db%8c/%d8%a2%d9%85%d9%88%d8%b2%d8%b4-%d8%ac%d8%a7%d9%85%d8%b9-%d9%88-%d9%be%d8%b1%d9%88%da%98%d9%87-%d9%85%d8%ad%d9%88%d8%b1-nodejs/"
                        >
                          nodejs
                        </a>
                      </span>
                      ،{" "}
                      <span style={{ color: "#0000ff" }}>
                        <a
                          style={{ color: "#0000ff" }}
                          href="https://reactapp.ir/courses/%d8%af%d9%88%d8%b1%d9%87-%d9%87%d8%a7%db%8c-%d8%a2%d9%85%d9%88%d8%b2%d8%b4%db%8c/%d8%a2%d9%85%d9%88%d8%b2%d8%b4-mongodb/"
                        >
                          mongodb{" "}
                        </a>
                      </span>
                      و{" "}
                      <span style={{ color: "#0000ff" }}>
                        <a
                          style={{ color: "#0000ff" }}
                          href="https://reactapp.ir/courses/%d8%af%d9%88%d8%b1%d9%87-%d9%87%d8%a7%db%8c-%d8%a2%d9%85%d9%88%d8%b2%d8%b4%db%8c/%d8%a2%d9%85%d9%88%d8%b2%d8%b4-graphql/"
                        >
                          graphql
                        </a>
                      </span>
                    </span>{" "}
                    یک اپلیکیشن فروشگاهی مشابه{" "}
                    <span style={{ color: "#000000" }}>
                      <a
                        style={{ color: "#000000" }}
                        href="https://digikala.com"
                      >
                        دیجی کالا
                      </a>{" "}
                    </span>
                    (react native) به همراه پنل مدیریت (react) و API برای اتصال
                    به سرور (nodejs ، mongodb و graphql) توسعه خواهیم داد.
                  </p>
                  <h2>
                    <strong>
                      چرا آموزش پروژه محور؟
                      <br />
                    </strong>
                  </h2>
                  <p className="text-end">
                    هدف ما در{" "}
                    <span style={{ color: "#000000" }}>
                      <a
                        style={{ color: "#000000" }}
                        href="https://reactapp.ir"
                      >
                        reactapp
                      </a>{" "}
                    </span>
                    از ابتدا ارائه آموزش های کاربردی و تخصصی در حوزه جاوااسکریپت
                    برای ورود به بازار کار بوده و باتوجه به آمار و مستندات
                    موجود،یادگیری زمانی در بهترین حالت اتفاق می افتد که بر روی
                    یک پروژه واقعی باشد.بنابراین یک آموزش پروژه محور بر پایه
                    کتابخانه های&nbsp; و فریمورک های جاوا اسکریپت آماده کردیم که
                    در قالب این دوره با استفاده از react native, node js,mongo
                    db,graphql&nbsp; و react js یک اپلیکیشن فروشگاهی مشابه دیجی
                    کالا به همراه پنل مدیریت به همراه Api ایجاد می کنیم.
                  </p>
                  <h2>
                    <strong>هدف این دوره؟</strong>
                  </h2>
                  <p>
                    هدف اصلی که ما در این دوره دنبال می کنیم، نشان دادن قدرت
                    جاوا اسکریپت است.یعنی شما با یادگیری جاوا اسکریپت می توانید
                    صفر تا صد یک اپلیکیشن فروشگاهی به همراه پنل مدیریت و بخش
                    سرور را بسازید.اگر شما بتوانید به تنهایی این موارد رو پیاده
                    سازی کنید یک full stack developer به حساب میاید که در بازار
                    کار به راحتی می تونید در position های عالی کار پیدا کنید.
                  </p>
                  <h2>
                    <strong>ویژگی های منحصر به فرد دوره</strong>
                  </h2>
                  <ul>
                    <li>کاملا پروژه محور و بر اساس یک نمونه واقعی</li>
                    <li>پشتیبانی کامل دوره</li>
                    <li>تدریس هر بخش توسط استاد متخصص آن حوزه</li>
                    <li>آموزش بر اساس نیاز بازار کار</li>
                    <li>تمرکز بر روی تکنولوژی های محبوب و پرکاربرد</li>
                    <li>بروز بودن دوره بر اساس آخرین نسخه های موجود</li>
                    <li>حرکت در مسیر فول استک (full stack) شدن</li>
                  </ul>
                  <h2>
                    <strong>
                      تکلیف پیش نیاز های&nbsp; این دوره چی میشه؟&nbsp;
                    </strong>
                  </h2>
                  <p className="text-right">
                    با توجه به اینکه تمامی تکنولوژی های استفاده شده در این دوره
                    بر پایه جاوا اسکریپت هستند، پس برای مشاهده این دوره باید
                    حتما به جاوا اسکریپت و ES6 مسلط باشید.علاوه بر این دو باید
                    آشنایی مقدماتی با react, react native ,node js و mongo db
                    داشته باشید که خوشبختانه این دوره ها به صورت رایگان در سایت
                    موجود است و شما می توانید با خیال راحت این دوره را شروع کنید
                  </p>
                  <ul>
                    <li>
                      <span style={{ color: "#0000ff" }}>
                        <a
                          style={{ color: "#0000ff" }}
                          href="https://reactapp.ir/courses/%d8%af%d9%88%d8%b1%d9%87-%d9%87%d8%a7%db%8c-%d8%a2%d9%85%d9%88%d8%b2%d8%b4%db%8c/%d8%a2%d9%85%d9%88%d8%b2%d8%b4-%d9%be%db%8c%d8%b4%d8%b1%d9%81%d8%aa%d9%87-%d8%ac%d8%a7%d9%88%d8%a7-%d8%a7%d8%b3%da%a9%d8%b1%db%8c%d9%be%d8%aa-javascript/"
                        >
                          <strong>آموزش جاوا اسکریپت</strong>
                        </a>
                      </span>
                    </li>
                    <li>
                      <span style={{ color: "#0000ff" }}>
                        <a
                          style={{ color: "#0000ff" }}
                          href="https://reactapp.ir/courses/%d8%af%d9%88%d8%b1%d9%87-%d9%87%d8%a7%db%8c-%d8%a2%d9%85%d9%88%d8%b2%d8%b4%db%8c/%d8%a2%d9%85%d9%88%d8%b2%d8%b4-%d8%ac%d8%a7%d9%88%d8%a7%d8%a7%d8%b3%da%a9%d8%b1%db%8c%d9%be%d8%aa-2015-es6/"
                        >
                          <strong>آموزش Es6</strong>
                        </a>
                      </span>
                    </li>
                    <li>
                      <span style={{ color: "#0000ff" }}>
                        <a
                          style={{ color: "#0000ff" }}
                          href="https://reactapp.ir/courses/%d8%af%d9%88%d8%b1%d9%87-%d9%87%d8%a7%db%8c-%d8%a2%d9%85%d9%88%d8%b2%d8%b4%db%8c/%d8%a2%d9%85%d9%88%d8%b2%d8%b4-reactjs-%d9%88%d8%b1%da%98%d9%86-16/"
                        >
                          <strong>آموزش react js</strong>
                        </a>
                      </span>
                    </li>
                    <li>
                      <span style={{ color: "#0000ff" }}>
                        <a
                          style={{ color: "#0000ff" }}
                          href="https://reactapp.ir/courses/%d8%af%d9%88%d8%b1%d9%87-%d9%87%d8%a7%db%8c-%d8%a2%d9%85%d9%88%d8%b2%d8%b4%db%8c/%d8%a2%d9%85%d9%88%d8%b2%d8%b4-%d9%85%d9%82%d8%af%d9%85%d8%a7%d8%aa%db%8c-react-native/"
                        >
                          <strong>آموزش react native</strong>
                        </a>
                      </span>
                    </li>
                    <li>
                      <span style={{ color: "#0000ff" }}>
                        <a
                          style={{ color: "#0000ff" }}
                          href="https://reactapp.ir/courses/%d8%af%d9%88%d8%b1%d9%87-%d9%87%d8%a7%db%8c-%d8%a2%d9%85%d9%88%d8%b2%d8%b4%db%8c/%d8%a2%d9%85%d9%88%d8%b2%d8%b4-mongodb/"
                        >
                          <strong>آموزش mongo db</strong>
                        </a>
                      </span>
                    </li>
                    <li>
                      <span style={{ color: "#0000ff" }}>
                        <a
                          style={{ color: "#0000ff" }}
                          href="https://reactapp.ir/courses/%d8%af%d9%88%d8%b1%d9%87-%d9%87%d8%a7%db%8c-%d8%a2%d9%85%d9%88%d8%b2%d8%b4%db%8c/%d8%a2%d9%85%d9%88%d8%b2%d8%b4-%d8%ac%d8%a7%d9%85%d8%b9-%d9%88-%d9%be%d8%b1%d9%88%da%98%d9%87-%d9%85%d8%ad%d9%88%d8%b1-nodejs/"
                        >
                          <strong>آموزش node js</strong>
                        </a>
                      </span>
                    </li>
                    <li>
                      <span style={{ color: "#0000ff" }}>
                        <a
                          style={{ color: "#0000ff" }}
                          href="https://reactapp.ir/courses/%d8%af%d9%88%d8%b1%d9%87-%d9%87%d8%a7%db%8c-%d8%a2%d9%85%d9%88%d8%b2%d8%b4%db%8c/%d8%a2%d9%85%d9%88%d8%b2%d8%b4-graphql/"
                        >
                          <strong>آموزش graph ql</strong>
                        </a>
                      </span>
                    </li>
                  </ul>
                  <p>
                    <strong>
                      با توجه به اینکه در زمان ضبط دوره، آخرین نسخه React
                      Navigation، نسخه 4 بوده است، به همین دلیل می توانید به
                      صورت رایکان در دوره{" "}
                      <a href="https://reactapp.ir/?p=49867">
                        React Navigation 5
                      </a>{" "}
                      ثبت نام کنید و از آخرین تغییرات این پکیج در پروژه های
                      خودتون استفاده کنید.
                    </strong>
                  </p>

                  <hr />
                </div>

                <div className={courseStyles.more}>
                  <span
                    className={courseStyles.jsCollapseBtn}
                    data-collapsed="نمایش بیشتر"
                    data-expand="بستن"
                  >
                    <i className="mdi mdi-chevron-down mdi-24px flex" />
                  </span>
                </div>
                <div className={courseStyles.infoBox}>
                  <div className="bg-orange-100 border-r-4 mt-12 rounded-md border-orange-500 text-orange-700 p-4">
                    راهنما ! جهت دریافت لینک دانلود تمامی قسمت ها بر روی این
                    لینک .کلیک کنید.
                  </div>
                </div>
              </div>
              <div
                className={
                  courseStyles.courseSingleContent +
                  " " +
                  courseStyles.courseFaq
                }
              >
                <div className={courseStyles.courseDesciption}>
                  <h1 className="my-4">سوالات متداول</h1>
                  {/* <AccordionFaq /> */}
                </div>
              </div>
              <div
                className={
                  courseStyles.courseSingleContent +
                  " " +
                  courseStyles.courseVideo
                }
              >
                <div className={courseStyles.courseDesciption}>
                  <h4 className="my-4">فهرستــــ ویدیوها</h4>
                  <div className={courseStyles.courseSingleTopPart}>
                    <div className={courseStyles.courseImageWrapper}>
                      <img
                        width="1667"
                        height="954"
                        src="https://d2ffcs5wrcif.cdn.shift8web.com/wp-content/uploads/LOW-3.jpg"
                        className="attachment-full size-full wp-post-image"
                        alt=""
                      />
                      <div className={courseStyles.videoButton}>
                        <Link href="/">
                          <span className="mdi mdi-play-outline flex justify-center items-center ml-2" />
                        </Link>
                      </div>
                    </div>
                  </div>
                  <div className={courseStyles.videoItem}>
                    <span className={courseStyles.videoItem__number}>1</span>
                    <div className={`${courseStyles.videoItem__title} mr-2`}>
                      مقدمه و معرفی دوره
                    </div>
                    <div className={courseStyles.videoItem__dlTime}>
                      <span>00:00:00</span>
                      <span className="mdi mdi-download-circle-outline" />
                    </div>
                  </div>
                </div>
              </div>
              <div className={courseStyles.courseReviews}>
                <div className={courseStyles.courseReviewTitle}>
                  <h3 className={courseStyles.inner}>
                    <span className="mdi mdi-more mdi-24px ml-2" />
                    <span>دوره های مرتبط</span>
                  </h3>
                </div>
                {/* <div className="row m-0 ">
                  <ShopCard
                    route={"/"}
                    SinglePageClass="course-item__single-page"
                  />
                </div> */}
              </div>
              <div className={courseStyles.courseReviews}>
                <div className={courseStyles.courseReviewTitle}>
                  <h3 className={courseStyles.inner}>
                    <span className="mdi mdi-comment-text-multiple mdi-24px ml-2" />
                    <span>نظرات دوره</span>
                  </h3>
                </div>
                <div className={courseStyles.courseComment}>
                  <ul className={courseStyles.courseComment__list}>
                    <li className={courseStyles.review}>
                      <div className={courseStyles.commentContainer}>
                        <div className={courseStyles.commentText}>
                          <div className={courseStyles.commentHeader}>
                            <h5 className={courseStyles.commentAuthor}>
                              spotify.abedi25924
                            </h5>

                            <time>مارس 28, 2022</time>
                          </div>
                          <div
                            className={courseStyles.studiareCommentReplayBtn}
                          >
                            <a
                              rel="nofollow"
                              className={courseStyles.commentReplyLink}
                              href="#comment-40922"
                            >
                              پاسخ
                            </a>
                          </div>
                          <div className={courseStyles.description}>
                            <p>
                              سلام خسته نباشید
                              <br />
                              من می خوام کل دوره یکجا دانلود کنم چیکار باید بکنم
                              ؟
                            </p>
                          </div>
                        </div>
                      </div>
                      <ul className={courseStyles.children}>
                        <li className={courseStyles.comment}>
                          <div className={courseStyles.commentContainer}>
                            <div className={courseStyles.commentAvatar}></div>

                            <div className={courseStyles.commentText}>
                              <div className={courseStyles.commentHeader}>
                                <h5 className={courseStyles.commentAuthor}>
                                  مهدی حسن زاده
                                  <em className={courseStyles.adminLabel}>
                                    (مدیریت)
                                  </em>{" "}
                                </h5>

                                <time>مارس 28, 2022</time>
                              </div>
                              <div
                                className={
                                  courseStyles.studiareCommentReplayBtn
                                }
                              >
                                <a
                                  rel="nofollow"
                                  className={courseStyles.commentReplyLink}
                                  href="#comment-40936"
                                  data-commentid="40936"
                                  data-postid="44501"
                                  data-belowelement="comment-40936"
                                  data-respondelement="respond"
                                  // data-replLinkyhref="پاسخ به مهدی حسن زاده"
                                  aria-label="پاسخ به مهدی حسن زاده"
                                >
                                  پاسخ
                                </a>
                              </div>{" "}
                              <div className={courseStyles.description}>
                                <p>
                                  سلام سلامت باشید
                                  <br />
                                  در بخش حساب کاربردی فایل های دوره در قالب فایل
                                  های زیپ قرار گرفته.با توجه به حجم بالای دوره
                                  امکان قرار دادن تمامی محتوا در یک فایل زیپ
                                  وجود ندارد
                                </p>
                              </div>
                            </div>
                          </div>
                        </li>
                      </ul>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div className="py-4 px-0 ">
            <div className={courseStyles.courseSingleAside}>
              <div className={courseStyles.courseInfoBox}>
                <div className={courseStyles.sellCourse}>
                  <strong>قیمت :</strong>
                  <p className={courseStyles.price}>
                    <del aria-hidden="true">
                      <span className={courseStyles.amount}>
                        269,000&nbsp;
                        <span>تومان</span>
                      </span>
                    </del>{" "}
                    <ins>
                      <span className={courseStyles.amount}>
                        108,000&nbsp;
                        <span className={courseStyles.PriceCurrencySymbol}>
                          تومان
                        </span>
                      </span>
                    </ins>
                  </p>
                </div>
                <button className="flex-shrink-0 bg-green-500 hover:bg-green-700 border-green-500 hover:border-green-700 text-sm border-4 text-white py-1 px-2 rounded w-full flex items-center justify-between">
                  <span className="mdi mdi-credit-card-check-outline mdi-24px" />
                  <span className="text-center">ثبت نام دوره</span>
                  <span />
                </button>
              </div>
              <div className={courseStyles.courseInfoBox}>
                <div className={courseStyles.courseMetaInfoList}>
                  <div className={courseStyles.totalSales}>
                    <span className="mdi mdi-download-outline mdi-24px " />
                    تعداد خرید / دانلود : <span>481</span>
                  </div>

                  <div className={courseStyles.metaInfoUnit}>
                    <div className={courseStyles.icon}>
                      <span className="mdi mdi-sitemap-outline" />
                    </div>
                    <div className={courseStyles.value}>
                      نوع دوره: غیرحضوری،ویدئویی
                    </div>
                  </div>

                  <div className={courseStyles.metaInfoUnit}>
                    <div className={courseStyles.icon}>
                      <span className="mdi mdi-book-open-page-variant-outline" />
                    </div>
                    <div className={courseStyles.value}>
                      سطح دوره: مقدماتی تا پیشرفته
                    </div>
                  </div>

                  <div className={courseStyles.metaInfoUnit}>
                    <div className={courseStyles.icon}>
                      <span className="mdi mdi-head-lightbulb-outline" />
                    </div>
                    <div className={courseStyles.value}>
                      پیش نیاز: html و css
                    </div>
                  </div>

                  <div className={courseStyles.metaInfoUnit}>
                    <div className={courseStyles.icon}>
                      <span className="mdi mdi-earth" />
                    </div>
                    <div className={courseStyles.value}>زبان: فارسی</div>
                  </div>

                  <div className={courseStyles.metaInfoUnit}>
                    <div className={courseStyles.icon}>
                      <span className="mdi mdi-clock-outline" />
                    </div>
                    <div className={courseStyles.value}>27ساعت و 21 دقیقه</div>
                  </div>

                  <div className={courseStyles.metaInfoUnit}>
                    <div className={courseStyles.icon}>
                      <span className="mdi mdi-format-list-numbered" />
                    </div>
                    <div className={courseStyles.value}>206 درس</div>
                  </div>

                  <div className={courseStyles.metaInfoUnit}>
                    <div className={courseStyles.icon}>
                      <span className="mdi mdi-sd" />
                    </div>
                    <div className={courseStyles.value}> 4.61 گیگابایت</div>
                  </div>

                  <div className={courseStyles.metaInfoUnit}>
                    <div className={courseStyles.icon}>
                      <span className="mdi mdi-cloud-download-outline" />
                    </div>
                    <div className={courseStyles.value}>
                      روش دریافت: دانلودی
                    </div>
                  </div>
                </div>
                <div className={courseStyles.progressTitle}>
                  <div className="flex">
                    <span className="mdi mdi-format-list-checks mdi-24px" />
                    <span className="mr-3"> درصد پیشرفت دوره: %100</span>
                  </div>
                  <div
                    className={courseStyles.meter + " " + courseStyles.animate}
                  >
                    <span style={{ width: "100%" }}>
                      <span></span>
                    </span>
                  </div>
                </div>
              </div>
              <div className={courseStyles.courseInfoBox}>
                <div className={courseStyles.stdBoxView}>
                  <span
                    className={`${courseStyles.courseViews} flex items-center`}
                  >
                    <span className="mdi mdi-account-eye-outline mdi-24px ml-2" />
                    <span>21.54k بازدید</span>
                  </span>
                  <span
                    className={`${courseStyles.courseReviewsCount} flex items-center`}
                  >
                    <span className="mdi mdi-comment-multiple-outline mdi-24px ml-2" />
                    <span> 77 دیدگاه</span>
                  </span>
                </div>
              </div>
              <div className={courseStyles.courseInfoBox}>
                <span className={courseStyles.taggedAs}>
                  <div className="flex items-center">
                    <span className="mdi mdi-tag-multiple-outline mdi-24px ml-1" />
                    <span className="ml-1">برچسب:</span>
                  </div>
                  <a
                    href="https://reactapp.ir/product-tag/%d8%a2%d9%85%d9%88%d8%b2%d8%b4-javascript/"
                    rel="tag"
                  >
                    آموزش javascript
                  </a>
                  <a
                    href="https://reactapp.ir/product-tag/%d8%a2%d9%85%d9%88%d8%b2%d8%b4-js/"
                    rel="tag"
                  >
                    آموزش js
                  </a>
                  <a
                    href="https://reactapp.ir/product-tag/%d8%a2%d9%85%d9%88%d8%b2%d8%b4-%d8%ac%d8%a7%d9%88%d8%a7-%d8%a7%d8%b3%da%a9%d8%b1%db%8c%d9%be%d8%aa/"
                    rel="tag"
                  >
                    آموزش جاوا اسکریپت
                  </a>
                  <a
                    href="https://reactapp.ir/product-tag/%d8%a2%d9%85%d9%88%d8%b2%d8%b4-%d9%81%d8%a7%d8%b1%d8%b3%db%8c-%d8%ac%d8%a7%d9%88%d8%a7-%d8%a7%d8%b3%da%a9%d8%b1%db%8c%d9%be%d8%aa/"
                    rel="tag"
                  >
                    آموزش فارسی جاوا اسکریپت
                  </a>
                  <a
                    href="https://reactapp.ir/product-tag/%db%8c%d8%a7%d8%af%da%af%db%8c%d8%b1%db%8c-%d8%ac%d8%a7%d9%88%d8%a7-%d8%a7%d8%b3%da%a9%d8%b1%db%8c%d9%be%d8%aa/"
                    rel="tag"
                  >
                    یادگیری جاوا اسکریپت
                  </a>
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
