import Head from "next/head";

import SlidersSection from "../src/components/fragments/sections/SlidersSection";
import PostsSection from "../src/components/fragments/sections/PostsSection";
import ServicesSection from "../src/components/fragments/sections/ServicesSection";
import AboutSection from "../src/components/fragments/sections/AboutSection";
import TeamSection from "../src/components/fragments/sections/TeamsSection";

import styles from "../styles/Home.module.css";
import { initMain } from "../src/services/mainService";

export default function Home({ data }) {
  const { sliders, pages } = data.data;

  return (
    <div className="continer">
      <Head>
        <title>بیمه کارآفرین نمیاندگی بابازاده</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <SlidersSection sliders={sliders} />
        <PostsSection styles={styles} pages={pages} />
        <ServicesSection styles={styles} />
        <AboutSection />
        <TeamSection styles={styles} />
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const response = await initMain();
  const data = await response.data;

  return {
    props: { data },
    revalidate: 10,
  };
}
